//******************************************************************************
//* clean.js
//*
//* Defines a custom gulp task for removing all output files that were 
//* autogenerated by other custom gulp tasks 
//******************************************************************************

var gulp = require("gulp"),
    del = require('del'),
    config = require('./@configuration.js');

gulp.task('clean', (done) => {

    var directories = [
        config.paths.dist,
        config.paths.lib,
        config.testing.testingRoot,
        config.debug.outputRoot,
        config.docs.output
    ];
    
    del(directories).then(() => done());
});